"""add_chat_models

Revision ID: 16546df84b7a
Revises: a118f2983f58
Create Date: 2026-02-26 07:23:25.968317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16546df84b7a'
down_revision: Union[str, Sequence[str], None] = 'a118f2983f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_conversations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_conversations_pkey'))
    )
    op.create_index(op.f('chat_conversations_id_idx'), 'chat_conversations', ['id'], unique=False)
    op.create_index(op.f('chat_conversations_user_id_idx'), 'chat_conversations', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('chat_messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('chat_messages_conversation_id_idx'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('chat_messages_id_idx'), 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chat_messages_id_idx'), table_name='chat_messages')
    op.drop_index(op.f('chat_messages_conversation_id_idx'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('chat_conversations_user_id_idx'), table_name='chat_conversations')
    op.drop_index(op.f('chat_conversations_id_idx'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
