"""add_candle_model

Revision ID: a118f2983f58
Revises: c1b86cfe6373
Create Date: 2026-02-26 07:05:50.871581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a118f2983f58'
down_revision: Union[str, Sequence[str], None] = 'c1b86cfe6373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('candles_asset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('candles_pkey')),
    sa.UniqueConstraint('asset_id', 'timeframe', 'timestamp', name='uq_candle_asset_tf_ts')
    )
    op.create_index(op.f('candles_id_idx'), 'candles', ['id'], unique=False)
    op.create_index(op.f('candles_timestamp_idx'), 'candles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('candles_timestamp_idx'), table_name='candles')
    op.drop_index(op.f('candles_id_idx'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
